### ISSUE TITLE
Random pix key validation

### ISSUE THREAD

**Issue by andersonpem** [Phillarmonic/cpf-cnpj#5]
Hey guys. I forgot about the Random type of pix key.
https://developers.international.pagseguro.com/reference/pix-key-validation-and-regex

It's similar to a UUID.

This is an enhancement of pix for privacy reasons, released after it was firstly launched in the market.

**Comment by phillarmonkey** [comment]
Hey man. Nice catch.

We can bump a minor version for that, as it's a feature addition that doesn't break any existing implementation.
I'll check when I can do it. If it's quick, you can add a PR as well. Please include unit tests covering the cases if you do so.

Obrigadão,
Z.

**Comment by phillarmonkey** [comment]
Although as it's characteristic of a PIX key, not a CPF or a CNPJ, we should move this to the other repo: https://github.com/Phillarmonic/pixicato-bundle/

**Comment by andersonpem** [comment]
Alright, closing here. :smiley:
